apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-repo-name  ### git repo-name
  namespace: argocd
spec:
  destination:
    namespace: git-repo-name ## this can be changed
    server: 'https://kubernetes.default.svc'
  source:
    path: helm
    repoURL: git@github.com-vap:Vapronixweb/testapp-k8.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default ####### project if any
  syncPolicy:
    syncOptions:      
    - CreateNamespace=true      
    automated:
      prune: true
      selfHeal: true

